const api = {
  adminLogin: (username, password) => login(username, password),
  getOperationsOverview: (snapshotDate) => request(`/admin/operations/overview${snapshotDate ? `?snapshot_date=${snapshotDate}` : ''}`),
  getCategories: () => request('/admin/categories'),
  createCategory: (data) => request('/admin/categories', { method: 'POST', body: JSON.stringify(data) }),
  updateCategory: (id, data) => request(`/admin/categories/${id}`, { method: 'PUT', body: JSON.stringify(data) }),
  deleteCategory: (id) => request(`/admin/categories/${id}`, { method: 'DELETE' }),
  getDishes: (params = {}) => request(`/admin/dishes?${new URLSearchParams(params)}`),
  createDish: (data) => request('/admin/dishes', { method: 'POST', body: JSON.stringify(data) }),
  updateDish: (id, data) => request(`/admin/dishes/${id}`, { method: 'PUT', body: JSON.stringify(data) }),
  deleteDish: (id) => request(`/admin/dishes/${id}`, { method: 'DELETE' }),
  getOrderMonitor: (params = {}) => request(`/admin/orders/monitor?${new URLSearchParams(params)}`),
  getOrders: (params = {}) => request(`/admin/orders?${new URLSearchParams(params)}`),
  getOrderDetail: (orderNo) => request(`/admin/orders/${orderNo}`),
  manualRefundOrder: (orderNo) => request(`/admin/orders/${orderNo}/manual-refund`, { method: 'PUT' }),
  getOrderStats: (date) => request(`/admin/orders/statistics?date=${date}`),
  confirmOrder: (orderNo) => request(`/admin/orders/${orderNo}/confirm`, { method: 'PUT' }),
  markOrderDelivering: (orderNo, courierId) => request(`/admin/orders/${orderNo}/delivering${courierId ? `?courier_id=${courierId}` : ''}`, { method: 'PUT' }),
  completeOrder: (orderNo) => request(`/admin/orders/${orderNo}/complete`, { method: 'PUT' }),
  getRawUsers: (params = {}) => request(`/admin/users?${new URLSearchParams(params)}`),
  getRawUser: (userId) => request(`/admin/users/${userId}`),
  getMemberSummary: () => request('/admin/members/summary'),
  getMemberUsers: (params = {}) => request(`/admin/members/users?${new URLSearchParams(params)}`),
  getUserCoupons: (userId) => request(`/admin/members/users/${userId}/coupons`),
  updateUserMemberStatus: (userId, data) => request(`/admin/members/users/${userId}/member`, { method: 'PUT', body: JSON.stringify(data) }),
  adjustUserPoints: (userId, data) => request(`/admin/members/users/${userId}/points`, { method: 'POST', body: JSON.stringify(data) }),
  issueUserCoupon: (userId, data) => request(`/admin/members/users/${userId}/coupons`, { method: 'POST', body: JSON.stringify(data) }),
  deleteUserCoupon: (userId, couponId) => request(`/admin/members/users/${userId}/coupons/${couponId}`, { method: 'DELETE' }),
  getCouriers: () => request('/admin/couriers'),
  createCourier: (data) => request('/admin/couriers', { method: 'POST', body: JSON.stringify(data) }),
  updateCourier: (id, data) => request(`/admin/couriers/${id}`, { method: 'PUT', body: JSON.stringify(data) }),
  deleteCourier: (id) => request(`/admin/couriers/${id}`, { method: 'DELETE' }),
  getConfig: () => request('/admin/config'),
  updateConfig: (data) => request('/admin/config', { method: 'PUT', body: JSON.stringify(data) })
};
